name: PR build

on:
  pull_request:
  push:
    branches-ignore:
      - "automated/dependency_version_update"
      - "automated/dependency_version_update_tmp"

jobs:
  ubuntu-build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Build with Gradle
        env:
          packageUser: ${{ github.actor }}
          packagePAT: ${{ secrets.GITHUB_TOKEN }}
          WORKING_DIR: ./graphql-cli
        run: |
            ./gradlew build codeCoverageReport --stacktrace --scan --console=plain --no-daemon
      - name: Generate Codecov Report
        uses: codecov/codecov-action@v2
